title: AkShare Backend API
description: 期货和股票数据 RESTful API 服务文档
remote_theme: just-the-docs/just-the-docs
url: "https://selfassets.github.io"
baseurl: "/actix-ak"

# Theme Settings
search_enabled: true
heading_anchors: false

# SEO & Sitemap
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
